version: '3.8'
services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - /mnt/db_data:/var/lib/mysql
    networks:
      - db_network

networks:
  db_network:
    driver: bridge