version: '3.8'

services:
  bookstack:
    image: linuxserver/bookstack
    environment:
      - DB_HOST=db
      - DB_USER=bookstack
      - DB_PASSWORD=password
      - DB_DATABASE=bookstack
      - APP_URL=http://192.168.64.4
      - APP_KEY=base64:t3J1MUhuhao7MVqEW6UtbpYwU5P8hro0Bo/Q9gtNsew=
    volumes:
      - /mnt/shared-storage/uploads:/config/uploads
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - backend

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - /mnt/db_data:/var/lib/mysql
    deploy:
      mode: global
    networks:
      - backend

  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend

networks:
  backend:
    driver: overlay